#
# filtered version of grid map visualization#
#

grid_map_topic: /filtered_grid_map
grid_map_visualizations:
  - name: gps_rtk_fix_type_filtered 
    type: point_cloud
    params:
     layer: gps_rtk_fix_type_filtered
  - name: gps_xy_acc_filtered 
    type: point_cloud 
    params:
     layer: gps_xy_acc_filtered 
  - name: accel_z_filtered 
    type: point_cloud
    params:
     layer: accel_z_filtered 
  - name: wheelpower_sum_filtered
    type: point_cloud
    params:
     layer: wheelpower_sum_filtered 
  - name: mowing_area
    type: occupancy_grid
    params:
     layer: mowing_area
     data_min: -0.2
     data_max: 1
